# yaml-language-server: $schema=https://taskfile.dev/schema.json
# - go install github.com/go-task/task/v3/cmd/task@latest

version: '3'

dotenv: ['.env']

vars:
  DB: 'postgres://{{.DB_USER}}:{{.DB_PASSWORD}}@localhost:5432/{{.DB_NAME}}?sslmode=disable'
  DBDOCKER: 'postgres://{{.DB_USER}}:{{.DB_PASSWORD}}@db:5432/{{.DB_NAME}}?sslmode=disable'
  N: '{{default "1" .N}}'

tasks:
  install:
    desc: Install all dependencies
    cmds:
      - go install github.com/vektra/mockery/v2@v2.53.6
      - go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
      - go install github.com/swaggo/swag/cmd/swag@v1.16.4
    silent: true
  
  mock:
    desc: Run generate mock
    cmds:
      - go generate ./...
    silent: true

  swagger:
    desc: generate swagger files
    cmds:
      - swag init -g internal/port/http/public/doc.go --parseDependency --parseInternal
    silent: true

  run-app-docker:
    desc: Run docker-compose
    cmds:
      - docker compose up -d
    silent: true

  down-app-docker:
    desc: Down docker-compose
    cmds:
      - docker compose down
    silent: true

  run-app:
    desc: Run app
    cmds:
      - PATH_CONFIG="config/cryptoservice.yaml" go run cmd/app/main.go
    silent: false

  migrate-docker-down-bystep:
    desc: Roll back migrations inside Docker (default N=1, set N=...)
    cmds:
      - docker compose run --rm migrator -path=/migrations/ -database="{{.DBDOCKER}}" down {{.N}}
    silent: true

  migrate-docker-up-bystep:
    desc: Run migrations inside Docker (default N=1, set N=...)
    cmds:
      - docker compose run --rm migrator -path=/migrations/ -database="{{.DBDOCKER}}" up {{.N}}
    silent: true

  migrate-docker-create:
    desc: Create a new migration (set NAME=...)
    requires:
      vars: [NAME]
    cmds:
      - docker compose run --rm migrator create -ext sql -dir /migrations -seq {{.NAME}}
    silent: true

  concreit-migrate-create:
    desc: Create migrations(set the value NAME=...)
    requires:
      vars: [NAME]
    cmds:
      - migrate create -ext sql -dir migrations -seq {{.NAME}}
    silent: true

  migrate-up:
    desc: Roll up migrations
    cmds:
      - migrate -source "file://migrations" -database "{{.DB}}" up
    silent: true

  migrate-up-bysteps:
    desc: Roll up migrations(set the value INT=...)
    requires:
      vars: [INT]
    cmds:
      - migrate -source "file://migrations" -database "{{.DB}}" up {{.INT}}
    silent: true

  migrate-down-bystep:
    desc: Roll back migrations(default N=1, set the value N=...)
    cmds:
      - migrate -source "file://migrations" -database "{{.DB}}" down {{.N}}
    silent: true

  migrate-down:
    desc: Roll back migrations
    cmds:
      - migrate -source "file://migrations" -database "{{.DB}}" down
    silent: true

  default:
    desc: Available tasks for this project
    cmds:
      - task --list
    silent: true
