// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/AMKrutikov/cryptoservice/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// CryptoProvider is an autogenerated mock type for the CryptoProvider type
type CryptoProvider struct {
	mock.Mock
}

type CryptoProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *CryptoProvider) EXPECT() *CryptoProvider_Expecter {
	return &CryptoProvider_Expecter{mock: &_m.Mock}
}

// GetActualRates provides a mock function with given fields: ctx, titles
func (_m *CryptoProvider) GetActualRates(ctx context.Context, titles []string) ([]*entities.Coin, error) {
	ret := _m.Called(ctx, titles)

	if len(ret) == 0 {
		panic("no return value specified for GetActualRates")
	}

	var r0 []*entities.Coin
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*entities.Coin, error)); ok {
		return rf(ctx, titles)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*entities.Coin); ok {
		r0 = rf(ctx, titles)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Coin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, titles)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CryptoProvider_GetActualRates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActualRates'
type CryptoProvider_GetActualRates_Call struct {
	*mock.Call
}

// GetActualRates is a helper method to define mock.On call
//   - ctx context.Context
//   - titles []string
func (_e *CryptoProvider_Expecter) GetActualRates(ctx interface{}, titles interface{}) *CryptoProvider_GetActualRates_Call {
	return &CryptoProvider_GetActualRates_Call{Call: _e.mock.On("GetActualRates", ctx, titles)}
}

func (_c *CryptoProvider_GetActualRates_Call) Run(run func(ctx context.Context, titles []string)) *CryptoProvider_GetActualRates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *CryptoProvider_GetActualRates_Call) Return(_a0 []*entities.Coin, _a1 error) *CryptoProvider_GetActualRates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CryptoProvider_GetActualRates_Call) RunAndReturn(run func(context.Context, []string) ([]*entities.Coin, error)) *CryptoProvider_GetActualRates_Call {
	_c.Call.Return(run)
	return _c
}

// NewCryptoProvider creates a new instance of CryptoProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCryptoProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *CryptoProvider {
	mock := &CryptoProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
