// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/AMKrutikov/cryptoservice/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// CryptoStorage is an autogenerated mock type for the CryptoStorage type
type CryptoStorage struct {
	mock.Mock
}

type CryptoStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *CryptoStorage) EXPECT() *CryptoStorage_Expecter {
	return &CryptoStorage_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *CryptoStorage) Close() {
	_m.Called()
}

// CryptoStorage_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type CryptoStorage_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *CryptoStorage_Expecter) Close() *CryptoStorage_Close_Call {
	return &CryptoStorage_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *CryptoStorage_Close_Call) Run(run func()) *CryptoStorage_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CryptoStorage_Close_Call) Return() *CryptoStorage_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *CryptoStorage_Close_Call) RunAndReturn(run func()) *CryptoStorage_Close_Call {
	_c.Run(run)
	return _c
}

// GetActualCoins provides a mock function with given fields: ctx, titles
func (_m *CryptoStorage) GetActualCoins(ctx context.Context, titles []string) ([]*entities.Coin, error) {
	ret := _m.Called(ctx, titles)

	if len(ret) == 0 {
		panic("no return value specified for GetActualCoins")
	}

	var r0 []*entities.Coin
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*entities.Coin, error)); ok {
		return rf(ctx, titles)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*entities.Coin); ok {
		r0 = rf(ctx, titles)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Coin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, titles)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CryptoStorage_GetActualCoins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActualCoins'
type CryptoStorage_GetActualCoins_Call struct {
	*mock.Call
}

// GetActualCoins is a helper method to define mock.On call
//   - ctx context.Context
//   - titles []string
func (_e *CryptoStorage_Expecter) GetActualCoins(ctx interface{}, titles interface{}) *CryptoStorage_GetActualCoins_Call {
	return &CryptoStorage_GetActualCoins_Call{Call: _e.mock.On("GetActualCoins", ctx, titles)}
}

func (_c *CryptoStorage_GetActualCoins_Call) Run(run func(ctx context.Context, titles []string)) *CryptoStorage_GetActualCoins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *CryptoStorage_GetActualCoins_Call) Return(_a0 []*entities.Coin, _a1 error) *CryptoStorage_GetActualCoins_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CryptoStorage_GetActualCoins_Call) RunAndReturn(run func(context.Context, []string) ([]*entities.Coin, error)) *CryptoStorage_GetActualCoins_Call {
	_c.Call.Return(run)
	return _c
}

// GetAggregateCoins provides a mock function with given fields: ctx, titles, aggType
func (_m *CryptoStorage) GetAggregateCoins(ctx context.Context, titles []string, aggType string) ([]*entities.Coin, error) {
	ret := _m.Called(ctx, titles, aggType)

	if len(ret) == 0 {
		panic("no return value specified for GetAggregateCoins")
	}

	var r0 []*entities.Coin
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) ([]*entities.Coin, error)); ok {
		return rf(ctx, titles, aggType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) []*entities.Coin); ok {
		r0 = rf(ctx, titles, aggType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Coin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, string) error); ok {
		r1 = rf(ctx, titles, aggType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CryptoStorage_GetAggregateCoins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAggregateCoins'
type CryptoStorage_GetAggregateCoins_Call struct {
	*mock.Call
}

// GetAggregateCoins is a helper method to define mock.On call
//   - ctx context.Context
//   - titles []string
//   - aggType string
func (_e *CryptoStorage_Expecter) GetAggregateCoins(ctx interface{}, titles interface{}, aggType interface{}) *CryptoStorage_GetAggregateCoins_Call {
	return &CryptoStorage_GetAggregateCoins_Call{Call: _e.mock.On("GetAggregateCoins", ctx, titles, aggType)}
}

func (_c *CryptoStorage_GetAggregateCoins_Call) Run(run func(ctx context.Context, titles []string, aggType string)) *CryptoStorage_GetAggregateCoins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(string))
	})
	return _c
}

func (_c *CryptoStorage_GetAggregateCoins_Call) Return(_a0 []*entities.Coin, _a1 error) *CryptoStorage_GetAggregateCoins_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CryptoStorage_GetAggregateCoins_Call) RunAndReturn(run func(context.Context, []string, string) ([]*entities.Coin, error)) *CryptoStorage_GetAggregateCoins_Call {
	_c.Call.Return(run)
	return _c
}

// GetCoinsList provides a mock function with given fields: ctx
func (_m *CryptoStorage) GetCoinsList(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCoinsList")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CryptoStorage_GetCoinsList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCoinsList'
type CryptoStorage_GetCoinsList_Call struct {
	*mock.Call
}

// GetCoinsList is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CryptoStorage_Expecter) GetCoinsList(ctx interface{}) *CryptoStorage_GetCoinsList_Call {
	return &CryptoStorage_GetCoinsList_Call{Call: _e.mock.On("GetCoinsList", ctx)}
}

func (_c *CryptoStorage_GetCoinsList_Call) Run(run func(ctx context.Context)) *CryptoStorage_GetCoinsList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *CryptoStorage_GetCoinsList_Call) Return(_a0 []string, _a1 error) *CryptoStorage_GetCoinsList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CryptoStorage_GetCoinsList_Call) RunAndReturn(run func(context.Context) ([]string, error)) *CryptoStorage_GetCoinsList_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: ctx, coins
func (_m *CryptoStorage) Store(ctx context.Context, coins []*entities.Coin) error {
	ret := _m.Called(ctx, coins)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*entities.Coin) error); ok {
		r0 = rf(ctx, coins)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CryptoStorage_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type CryptoStorage_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - coins []*entities.Coin
func (_e *CryptoStorage_Expecter) Store(ctx interface{}, coins interface{}) *CryptoStorage_Store_Call {
	return &CryptoStorage_Store_Call{Call: _e.mock.On("Store", ctx, coins)}
}

func (_c *CryptoStorage_Store_Call) Run(run func(ctx context.Context, coins []*entities.Coin)) *CryptoStorage_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*entities.Coin))
	})
	return _c
}

func (_c *CryptoStorage_Store_Call) Return(_a0 error) *CryptoStorage_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CryptoStorage_Store_Call) RunAndReturn(run func(context.Context, []*entities.Coin) error) *CryptoStorage_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewCryptoStorage creates a new instance of CryptoStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCryptoStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *CryptoStorage {
	mock := &CryptoStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
