// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/AMKrutikov/cryptoservice/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// GetActualCoins provides a mock function with given fields: ctx, titles
func (_m *Storage) GetActualCoins(ctx context.Context, titles []string) ([]*entities.Coin, error) {
	ret := _m.Called(ctx, titles)

	if len(ret) == 0 {
		panic("no return value specified for GetActualCoins")
	}

	var r0 []*entities.Coin
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*entities.Coin, error)); ok {
		return rf(ctx, titles)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*entities.Coin); ok {
		r0 = rf(ctx, titles)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Coin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, titles)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_GetActualCoins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActualCoins'
type Storage_GetActualCoins_Call struct {
	*mock.Call
}

// GetActualCoins is a helper method to define mock.On call
//   - ctx context.Context
//   - titles []string
func (_e *Storage_Expecter) GetActualCoins(ctx interface{}, titles interface{}) *Storage_GetActualCoins_Call {
	return &Storage_GetActualCoins_Call{Call: _e.mock.On("GetActualCoins", ctx, titles)}
}

func (_c *Storage_GetActualCoins_Call) Run(run func(ctx context.Context, titles []string)) *Storage_GetActualCoins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *Storage_GetActualCoins_Call) Return(_a0 []*entities.Coin, _a1 error) *Storage_GetActualCoins_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_GetActualCoins_Call) RunAndReturn(run func(context.Context, []string) ([]*entities.Coin, error)) *Storage_GetActualCoins_Call {
	_c.Call.Return(run)
	return _c
}

// GetAggregateCoins provides a mock function with given fields: ctx, titles, aggType
func (_m *Storage) GetAggregateCoins(ctx context.Context, titles []string, aggType string) ([]*entities.Coin, error) {
	ret := _m.Called(ctx, titles, aggType)

	if len(ret) == 0 {
		panic("no return value specified for GetAggregateCoins")
	}

	var r0 []*entities.Coin
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) ([]*entities.Coin, error)); ok {
		return rf(ctx, titles, aggType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) []*entities.Coin); ok {
		r0 = rf(ctx, titles, aggType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Coin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, string) error); ok {
		r1 = rf(ctx, titles, aggType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_GetAggregateCoins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAggregateCoins'
type Storage_GetAggregateCoins_Call struct {
	*mock.Call
}

// GetAggregateCoins is a helper method to define mock.On call
//   - ctx context.Context
//   - titles []string
//   - aggType string
func (_e *Storage_Expecter) GetAggregateCoins(ctx interface{}, titles interface{}, aggType interface{}) *Storage_GetAggregateCoins_Call {
	return &Storage_GetAggregateCoins_Call{Call: _e.mock.On("GetAggregateCoins", ctx, titles, aggType)}
}

func (_c *Storage_GetAggregateCoins_Call) Run(run func(ctx context.Context, titles []string, aggType string)) *Storage_GetAggregateCoins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(string))
	})
	return _c
}

func (_c *Storage_GetAggregateCoins_Call) Return(_a0 []*entities.Coin, _a1 error) *Storage_GetAggregateCoins_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_GetAggregateCoins_Call) RunAndReturn(run func(context.Context, []string, string) ([]*entities.Coin, error)) *Storage_GetAggregateCoins_Call {
	_c.Call.Return(run)
	return _c
}

// GetCoinsList provides a mock function with given fields: ctx
func (_m *Storage) GetCoinsList(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCoinsList")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_GetCoinsList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCoinsList'
type Storage_GetCoinsList_Call struct {
	*mock.Call
}

// GetCoinsList is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Storage_Expecter) GetCoinsList(ctx interface{}) *Storage_GetCoinsList_Call {
	return &Storage_GetCoinsList_Call{Call: _e.mock.On("GetCoinsList", ctx)}
}

func (_c *Storage_GetCoinsList_Call) Run(run func(ctx context.Context)) *Storage_GetCoinsList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Storage_GetCoinsList_Call) Return(_a0 []string, _a1 error) *Storage_GetCoinsList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_GetCoinsList_Call) RunAndReturn(run func(context.Context) ([]string, error)) *Storage_GetCoinsList_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: ctx, coins
func (_m *Storage) Store(ctx context.Context, coins []*entities.Coin) error {
	ret := _m.Called(ctx, coins)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*entities.Coin) error); ok {
		r0 = rf(ctx, coins)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type Storage_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - coins []*entities.Coin
func (_e *Storage_Expecter) Store(ctx interface{}, coins interface{}) *Storage_Store_Call {
	return &Storage_Store_Call{Call: _e.mock.On("Store", ctx, coins)}
}

func (_c *Storage_Store_Call) Run(run func(ctx context.Context, coins []*entities.Coin)) *Storage_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*entities.Coin))
	})
	return _c
}

func (_c *Storage_Store_Call) Return(_a0 error) *Storage_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_Store_Call) RunAndReturn(run func(context.Context, []*entities.Coin) error) *Storage_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
