service_name: crypto_service
version: 1.0

port:
  http:
    public: 8080
    timeout: 5s

storage:
  type: postgres
postgres:
  connection_string: postgres://postgres:123456@localhost:5432/postgres?sslmode=disable

providers:
  coingecko:
    api_key: "CG-SdGMn7C5Rv2F4hTMwLdJ1Pk6"